# Generated by Django 4.2.4 on 2023-10-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
                ('Conclusion', models.TextField()),
                ('meta_titile', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=200)),
                ('focus_keyword', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='media/images')),
            ],
            options={
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
