# Generated by Django 4.2.4 on 2023-09-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=500)),
                ('features', models.CharField(max_length=500)),
                ('usecase', models.CharField(max_length=500)),
                ('hashtag', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=255)),
                ('image', models.ImageField(upload_to='media/images')),
            ],
            options={
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
